pathToSpeachSynth = "/usr/bin/espeak"
pathToMecab="/usr/bin/mecab"
Mecab_Dictionary_path="/home/amigojapan/projects/ejspeak/dictionary/mecab-jumandic-7.0-20130310"
parametersToSpeachSynthJP="-v es-mx -s 80 -f "
parametersToSpeachSynthEN="-f "
tempfile="speak_this.tmp"