pathToSpeachSynth = "~/Downloads/espeak-1.45.04-OSX/espeak-1.45.04/speak"
parametersToSpeachSynthJP="-v es-mx -s 80 -f "
parametersToSpeachSynthEN="-f "
tempfile="speak_this.tmp"
pathToMecab="/usr/local/bin/mecab"
Mecab_Dictionary_path="~/Downloads/mecab-jumandic-7.0-20130310/"